mysite/library/urls.py
from django.urls import path, include
from . import views
from unicodedata import name

# Sukuriame marsrutus
urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),

    # <int:author_id> - nurodome, kad nukreipimas marsruto bus papildomas argumentas su integer kintamuoju author_id
    # name: author-detail - paimamas is models, klases Author, funkcijos  "get_absolute_url"
    # views.author - funkcija bus aprasyta views faile
    # cia ivedus authors/(skaicius) gausime nauja langa, kuris nuves i autoriu, kurio klases id - (skaicius)
    path('authors/<int:author_id>', views.author, name='author-detail'),

    # views.BookListView - sukurta papildoma klase views faile
    path('books/', views.BookListView.as_view(), name='books'),

    # views.BookDetailView
    # <int:pk> - sujungimas per primary key
    # book-detail - reverse is Book klases models.py faile
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),

    # sukuriamas paieskos lauko marsutas. Funkcionalumas aprasomas bus views.py 'search' funkcijoje
    path('search/', views.search, name='search'),

    # Kuriame useriu prisijungima
    # djangocontrib.auth.urls - vienas is django jau paruostu marsrutu, leidzia prijungti urls is 'auth'
    path("accounts/", include("django.contrib.auth.urls")),

    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),
    path('mybooks/new', views.BookByUserCreateView.as_view(), name='my-borrowed-new'),
    path('mybooks/<uuid:pk>', views.BookByUserDetailView.as_view(), name='my-book'),
    path('mybooks/<uuid:pk>/update', views.BookByUserUpdateView.as_view(), name='my-book-update'),
    path('mybooks/<uuid:pk>/delete', views.BookByUserDeleteView.as_view(), name='my-book-delete')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('library/', include("library.urls")),
    path('admin/', admin.site.urls),
    # sukuriame nukreipima, kad butu automatiskai nukreipiama i library einant i homepage
    path('', RedirectView.as_view(url='library/', permanent=True)),
    # pridedame tinymce
    path('tinymce/', include('tinymce.urls'))
    # pridedame styles is library/static/css/styles.css / Nurodome kelia link settings directorijos
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # pridedame media file'us ir nurodome kelia link ju

mysite/library/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date
from tinymce.models import HTMLField  # ikelia redaktoriu ir priemones texto formatavimui. Very cool
from PIL import Image  # redaguosime paveiksliuko dydi profiliui

# Create your models here.


class Genre(models.Model):
    name = models.CharField('Pavadinimas', max_length=200, help_text='Iveskite knygos zanra')

    def __str__(self):
        return self.name

    # Pakeicia suanglinima frameworke i musu pasirinktus isvedimus
    class Meta:
        verbose_name = "Zanras"
        verbose_name_plural = "Zanrai"


class Book(models.Model):
    title = models.CharField('Pavadinimas', max_length=200)
    # susirisa autoriai su savo knygomis
    # related name - sukuria kintamojo rysi, kuri bus galima naudoti kitoje, suristoje klaseje
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True, related_name='books')
    summary = models.TextField('Aprasymas', max_length=1000, help_text='Trumpas knygos aprasymas')
    isbn = models.CharField('ISBN', max_length=13)
    # Rysys daug su daug
    genre = models.ManyToManyField(Genre, help_text='Isrinkite zanra knygai')

    # Sukuriame papildoma lauka paveiksliuku patalpinimui
    cover = models.ImageField('Virselis', upload_to='covers', null=True, blank=True)
    # NOTE: jeigu ikeliant paveiksliuka admino lange meta errora, admin.py faile istrinti atitinkamus readonlyfields

    # Skirta ispakuoti genre elementus, kad galetume atvaizduoti
    def display_genre(self):
        return '; '.join([genre.name for genre in self.genre.all()])
    # .join nera butinas atvaizdavimui, taciau tai yra saugiau, kadangi isvedamas string, o ne listas

    # Pervadiname isvesti framerworke. Vietoje Display Genre, bus rodoma 'Zanras'
    display_genre.short_description = 'Zanras'

    def __str__(self):
        return f'{self.title}'

    # Gauname linka
    def absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    # Pakeicia suanglinima frameworke i musu pasirinktus isvedimus
    class Meta:
        verbose_name = "Knyga"
        verbose_name_plural = "Knygos"


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unikalus knygos kopijos ID')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    due_back = models.DateField('Bus prieinama', null=True, blank=True)
    LOAN_STATUS = (
        ('a', 'Administruojama'),
        ('p', 'Paimta'),
        ('g', 'Galima paimti'),
        ('r', 'Rezervuota')
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
        help_text='Status'
    )

    # Sukuriame vartotojui sasaja. Vienas vartotojas gales skolintis daug knygu, todel kuriame ForeignKey
    # User importuotas is django bibliotekos django.contrib.auth.models
    reader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    # papildomas parametras, kuris tikrins ar knyga jau turejo buti grazinta

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        else:
            return False

    # nustatomas rykiavimas pagal (due back)
    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} {self.book.title}'


class Author(models.Model):
    first_name = models.CharField('Vardas', max_length=100)
    last_name = models.CharField('Pavarde', max_length=100)
    # description = models.TextField('Aprasymas', max_length=2000, default='Biografija')

    description = HTMLField()

    # Skirta ispakuoti Author elementus, kad galetume atvaizduoti
    # Jungiasi su klaseje Book, kintamajame 'author' sukurtame "related_name='books'"
    def display_books(self):
        return ', '.join([book.title for book in self.books.all()[:3]])

    display_books.short_description = "Knygos"

    class Meta:
        ordering = ['last_name', 'first_name']
        verbose_name = "Autorius"
        verbose_name_plural = "Autoriai"

    # sulinkinimas i konkrecia objekto eilute. Reversu suformuoja rysi su pavadinimu 'author-detail' ir argumentu
    # args=[str(self.id)]
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class BookReview(models.Model):
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    # auto_now_add - automatiskai objekto sukurimo metu ides data ir laika
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Atsiliepimas', max_length=2000)


# Klase skirta vartotojo profilio kurimui ir taisymui
# profilius useriams reiktu rankiniu budu priskirti, taciau galima automatizuoti: python manage.py shell ->
# -> from django.contrib.auth.models import User -> from library.models import Profilis ->
# -> for user_obj in User.objects.all(): -> (indent)profile_obj = Profilis(user=user_obj) -> profile_obj.save()
class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # susieja vienas su vienu django Modeli USER
    nuotrauka = models.ImageField(default='default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} profilis'

    # Keiciame paveikslelio dydi, jeigu neatitinka parametru
    def save(self, *args, **kwargs):  # perrasome save metoda is Model klases, kuri paveldeta Profilis klases
        super().save(*args, **kwargs)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)



# pabaigus komanda terminale: python manage.py makemigrations
# python manage.py migrate

mysite/library/forms.py
from .models import BookReview, Profilis, BookInstance
from django import forms
from django.contrib.auth.models import User


class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ('content', 'book', 'reviewer')
        widgets = {'book': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email')
        widgets = {'username': forms.HiddenInput()}


class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['nuotrauka']  # gali buti ir tuple


class DateInput(forms.DateInput):
    input_type = 'date'


class UserBookCreateForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ('book', 'reader', 'due_back', 'status')
        widgets = {'reader': forms.HiddenInput, 'due_back': DateInput}  # DateInput ismes drop-down kalendoriu

mysite/library/templates/author.html
{% extends "base.html" %}
{% block content %}
<div>
  <h4>{{author.first_name}} {{author.last_name}}</h4>
  <!-- hr - ideda brugsneeeli -->
  <hr/>
  <!-- ikeliame i puslapy klases Author description -->
  <p>{{author.description | safe }}</p> <!-- safe leidzia matyti texto formatavima ikelta is db (tinymce etc.)-->
  <hr/>
  <h5>Mes turime sias {{author.first_name}} {{author.last_name}} knygas: </h5>
  <ul>
    {%  for book_obj in author.books.all %}
    <li> {{book_obj.title}} </li>
    {% endfor %}
  </ul>

</div>
{% endblock %}

mysite/library/templates/authors.html
{% extends "base.html" %}
{% block content %}
<h1>Autoriai</h1>
<p>Musu knygu autoriu sarasas: </p>
{% for author_obj in authors %}
<!-- author-detail imamamas is Author klases, funkcijos get_absolute_url. Funkcija sukuria back-linka -->
<li><a href="{% url 'author-detail' author_obj.id %}">{{author_obj}}</a></li>
{% endfor %}

<div class="container puslapiai"><nav aria-label="...">
        {% if authors.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in authors.paginator.page_range %}
                    {% if authors.number == i %}
                        <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav></div>

{% endblock %}

mysite/library/templates/base_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Biblioteka</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Pradžia</a></li>
                <li><a href="{% url 'books' %}">Visos knygos</a></li>

                 <!--Sujungiame marsruta "authors" is library/urls / name="authors"-->
                <li><a href="{% url 'authors' %}">Visi autoriai</a></li>

                <!--Paieskos lauko kurimas. Laukas atsiras po Autoriai, Knygos linkais-->
                <li>
                    <form action="{% url 'search' %}" method="get" class="form-inline">
                        <input name="query" class="form-control" type="text" placeholder="Paieska">
                        <!--Pridedam mygtuka-->
                        <button class="btn btn-secondary" type="submit">Ieskoti</button>
                    </form>
                </li>

            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
</div>
</body>
{# cia yra Jinja komentaras #}
</html>

mysite/library/templates/book_detail.html
{% extends "base.html" %}
{% block content %}
<!-- book atsiranda is BookDetailView-->
<h1>{{book.title}}</h1>
<p><b>Autorius: </b><a href="{% url 'author-detail' book.author.id %}"> {{book.author}}</a></p>
<p><b>Aprasymas:</b> {{book.summary}}</p>
<p><b>ISBN: </b>{{book.isbn}}</p>
<p><b>Zanras: </b>{{book.genre.all|join:", "}}</p> <!-- |join:"," skirta sujungti elementus, kurie sustatyti ManyToMany -->

<h4><b>Turimu kopiju statusas: </b></h4>
{% for book_inst_obj in book.bookinstance_set.all %}
<hr>
<!--get_status_display atitikmuo: .get(), status .get(status), display - parodo rakto reiksme. Siuo budu issitraukiame
reiksmes naudojant zodynu raktus
-->
<p>{{book_inst_obj.get_status_display}}</p>

<p>Planuojama grazinimo data i biblioteka: {{book_inst_obj.due_back}}</p>
<p>Kopijos ID: {{book_inst_obj.id}}</p>
{%endfor%}

{% endblock %}

mysite/library/templates/book_detail_styled.html
{% extends "base.html" %}
{% block content %}
<!-- book atsiranda is BookDetailView-->
<h1>{{book.title}}</h1>
<p><b>Autorius: </b><a href="{% url 'author-detail' book.author.id %}"> {{book.author}}</a></p>
<p><b>Aprasymas:</b> {{book.summary}}</p>
<p><b>ISBN: </b>{{book.isbn}}</p>
<p><b>Zanras: </b>{{book.genre.all|join:", "}}</p> <!-- |join:"," skirta sujungti elementus, kurie sustatyti ManyToMany -->

<!--Bus ivedami atsiliepimai-->
<hr>
{% if user.is_authenticated %}
<div class="fieldWrapper">
    <h4>Palikite atsiliepima:</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.content }}  <!--sugeneruota is django.views.generic.edit import FormMixin-->
        <br>
        <input type="submit", value="Palikti atsiliepima">
    </form>
</div>
{% endif %}

<!--Bus rodomi atsiliepimai is models.py BookReview klases-->
<hr>
<h4>Atsiliepimai</h4>
{% if book.bookreview_set.all %}  <!--tikriname ar is viso yra atsiliepimu tam tikroje knygoje-->
{% for book_review_obj in book.bookreview_set.all %}
<hr>
<p>{{book_review_obj.reviewer}}, <em>{{book_review_obj.date_created}}</em></p>  <!--iskvieciamas useris (su data), kuris atsiliepima paliko-->
<p>{{book_review_obj.content}}</p>
{% endfor %}
{% else %}
<p>Knyga neturi atsiliepimu</p>
{% endif %}

<!--isfiltruojamos turimos kopijos is BookInstance-->
<hr>
<h4><b>Turimu kopiju statusas: </b></h4>
{% for book_inst_obj in book.bookinstance_set.all %}

<!--get_status_display atitikmuo: .get(), status .get(status), display - parodo rakto reiksme. Siuo budu issitraukiame
reiksmes naudojant zodynu raktus
class="text-success" - nuspalvina zalia spalva
class="text-danger" - nuspalvina raudona spalva
class="text-warning" - nuspalvina geltona spalva
-->
<p class="{% if book_inst_obj.status == 'g' %}text-success
{% elif book_inst_obj.status == 'p' %}text-danger
{% else %}text-warning
{% endif %}">{{book_inst_obj.get_status_display}}</p>

{% if book_inst_obj.status != 'g'%}
<p>Planuojama, kad knyga bus prieinama nuo: {{book_inst_obj.due_back}}</p>
{% endif %}

<!-- class="text-muted" - nudazo pilkai-->
<p class="text-muted"><strong>Kopijos ID:</strong> {{book_inst_obj.id}}</p>
{%endfor%}

{% endblock %}

mysite/library/templates/book_list.html
{% extends "base.html" %}
{% block content %}

<!--ijungiame static komandas-->
{% load static%}

<h1>Knygu sarasas: </h1>

<!-- book_list automatiskai sugeneruotas is klases BookListView -->
{%  if book_list %}
<!--Sukuriame apipavidalinima paveiksliukams-->
<div class="row">
    {%  for book_obj in book_list %}
    <!--Aprasomas rodomo vaizdo stilius su paveiksliukais-->
    <div class="col -md4 d-flex align-items-stretch">
        <div class="card mb-4 shadow-sm", style="width: 14rem;">
            <!--Jeigu paveiksliukas yra-->
            {% if book_obj.cover %}
                <img src="{{book_obj.cover.url}}" class="card-img-top" width="100" height="200">
            <!--Kas rodoma, jeigu nera ikelto paveiksliuko-->
            {% else %}
                <img src="{% static 'img/no-image.png'%}" class="card-img-top">
            {% endif %}
        </div>
        <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">{{book_obj.author}}</h6>
            <!--sukuriame linka knygoms-->
            <p class="card-text"><a class="card-link" href="{{book_obj.id}}">{{book_obj.title}}</a></p>
        </div>

    </div>
    {% endfor %}
</div>
{% else %}
<p>Bibliotekoje knygu nera</p>
{% endif %}

<!-- puslapio PUSLAPIAVIMO aprasymas-->
<div class="pagination"><span class="step-links">
        <!--Kas rodoma, jeigu puslapis nera pirmas-->
        <!--page_obj - paginator elementas ateinantis is paginaty_by, aprasytoje view.py, BookListView klaseje-->
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a><a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

         <!-- span - grupavimo elementas-->
        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}</span>

        <!-- Kas rodoma kai pusplapis nera paskutinis-->
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a><a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span></div>

{% endblock %}

mysite/library/templates/index.html
{% extends "base.html" %}
{% block content %}

<h1>Rajono biblioteka</h1>
<p>Sveiki atvyke i knygu roju!</p>
<p>Siuo metu turime:</p>
<ul>
    <li>Knygu: {{num_books}}</li>
    <li>Egzemplioriu: {{num_instances}} </li>
    <li>Laisvu egzemplioriu: {{num_instances_available}}</li>
    <li>Autoriu: {{num_authors}}</li>
</ul>
<p>Sveiki, {{user}}</p>
<p>Cia jus lankotes: {{num_visits}} karta </p>

{% endblock %}

mysite/library/templates/profilis.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <div class="media">
    <img src="{{user.profilis.nuotrauka.url}}" class="rounded-circle account-mg">
    <div class="media-body">
      <h2 class="account-heading">{{user.username}}</h2>
      <p class="text-secondary">{{user.email}}</p>
    </div>
  </div>
  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Profilio info</legend>
      {{u_form | crispy}}
      {{p_form | crispy}}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
    </div>
  </form>
</div>

{% endblock %}

mysite/library/templates/register.html
{% extends "base.html" %}

{% block content %}

<div class="container register"><h3>Registracija</h3><br/>
    <form method="post">
        {% csrf_token %}
        <div class="form-group"><label for="username">Vartotojo vardas</label><input name="username" type="text"
                                                                                     class="form-control" id="username"
                                                                                     aria-describedby="usernameHelp"><small
                id="usernameHelp" class="form-text text-muted">Iki 150 simbolių.</small></div>
        <div class="form-group"><label for="exampleInputEmail1">El. paštas</label><input name="email" type="email"
                                                                                         class="form-control"
                                                                                         id="exampleInputEmail1"
                                                                                         aria-describedby="emailHelp"><small
                id="emailHelp" class="form-text text-muted">Nesidalinsime su niekuo, nesiųsime jokio spamo.
            Reikalingas naujam slaptažodžiui išsiųsti. </small></div>
        <div class="form-group"><label for="password">Slaptažodis</label><input name="password" type="password"
                                                                                class="form-control" id="password"
                                                                                aria-describedby="pwdHelp"><small
                id="pwdHelp" class="form-text text-muted">Ne mažiau, kaip 8 simboliai. Negali būti vien tik
            skaičiai</small></div>
        <div class="form-group"><label for="password2">Pakartoti slaptažodį</label><input name="password2"
                                                                                          type="password"
                                                                                          class="form-control"
                                                                                          id="password2"
                                                                                          aria-describedby="pwd2Help">
        </div>
        <button type="submit" class="btn btn-primary register-button">Registruotis</button>
    </form>
    <p>Jeigu užsiregistravote anksčiau, <a href="{% url 'login'%}?next=/library"><strong>prisijunkite.</strong></a></p></div>

{% endblock %}

mysite/library/templates/search.html
{% extends "base.html" %}
{% block content %}
<!-- paduodama pagal query rakta is views.py search funkcijos-->
<h1>Paieskos pagal {{query}} rezultatai: </h1>
<!-- paduodama pagal books rakta is views.py search funkcijos
Nurodome kas vyks kai bus kazkas surasta-->
{% if books %}
<ul>
  {% for book_obj in books %}
    <li>
      <a href="{% url 'book-detail' book_obj.id %}"> {{book_obj.title}}</a>
        {{book_obj.isbn}} {{book_obj.author}}
    </li>
  {% endfor %}
</ul>
{% else %}
<p>Nieko nerasta</p>
{% endif %}

{% endblock %}

mysite/library/templates/user_book.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>Mano paimta knyga</h1>
<h4>{{user}}</h4>
{% if bookinstance.book.cover %}
<img src="{{bookinstance.book.cover.url}}"/>
{% else %}
<img src="{% static 'img/no-image.png' %}"/>
{% endif %}
<hr>
<h5>{{bookinstance.book}} - {{bookinstance.book.author}} </h5>
<p>Egzempliorius ID: {{bookinstance.pk}}</p>
<p class="{% if bookinstance.is_overdue %}text-danger{% endif %}">Grazinti iki: {{bookinstance.due_back}}</p>
<div>
    <!-- bookinstance.pk bus nukreiptas i urls.py mybooks/<uuid:pk>/update, konkreciai i <uuid:pk>-->
    <a href="{% url 'my-book-update' bookinstance.pk %}" class="btn btn-secondary btn-sm">Redaguoti</a>
    <a href="{% url 'my-book-delete' bookinstance.pk %}" class="btn btn-secondary btn-sm">Istrinti</a>
</div>
{% endblock %}

mysite/library/templates/user_book_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Ištrinti knygą</legend>
            <h2>Ar tikrai norite ištrinti knygą su ID: {{ bookinstance.pk }}?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Taip, ištrinti</button>
            <a class="btn btn-outline-secondary" href="{% url 'my-book' object.id %}">Atšaukti</a></div>
    </form>
</div>
{% endblock content %}

mysite/library/templates/user_book_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Kurti/Redaguoti knygos egzemplioriu</legend>
      {{ form | crispy }}
      <button class="btn btn-outline-info" type="submit">Issaugoti</button>
    </fieldset>
  </form>
</div>

{% endblock %}

mysite/library/templates/user_books.html
{% extends "base.html" %}
{% block content %}

<h1>Mano paimtos knygos</h1>
<img src="{{user.profilis.nuotrauka.url}}" class="rounded-circle account-mg">
{% if bookinstance_list %}
<ul>
    {% for bookinstance_obj in bookinstance_list %}
        <li class="{% if bookinstance_obj.is_overdue %}text-danger{%endif%}">
            <a href="{% url 'book-detail' bookinstance_obj.book.pk %}">{{bookinstance_obj.book.title}}</a>
            Grazinti iki: {{bookinstance_obj.due_back}}
            <p><a href="{% url 'my-book' bookinstance_obj.id %}"> Keisti - {{bookinstance_obj.id}}</a></p>
        </li>
    {%endfor%}
</ul>
{%else%}
<p>Siuo metu nesate paeme jokiu knygu</p>
{%endif%}
{% endblock %}